### ISSUE TITLE
Use Jetty 9.3

### ISSUE THREAD

**Issue by berezovskyi** [eclipse/lyo.rio#15]
https://github.com/eclipse/lyo.rio/blob/master/rio-oslc4j/org.eclipse.lyo.oslc4j.changemanagement/pom.xml uses Jetty 9.2 which might have trouble working under JDK 8; 9.4 on my machine had some strange issues, I suspect either something in our code/Wink is causing it or we need to migrate to JDK 9+ for that.

**Comment by jamsden** [comment]
We need to be careful to not get too far ahead of our OSLC4J users with JDK, Jetty, Jersey, etc. Otherwise people with stick with 2.4.0.

**Comment by berezovskyi** [comment]
I suggest we stick to JDK 8 for a foreseeable future. But we should update the dependencies as need.

On 2019-01-23 , at 13:07, Jim Amsden <notifications@github.com<mailto:notifications@github.com>> wrote:


We need to be careful to not get too far ahead of our OSLC4J users with JDK, Jetty, Jersey, etc. Otherwise people with stick with 2.4.0.

**Comment by jadelkhoury** [comment]
Agree with jim’s Warning. 
But we can’t escape from introducing  Jersey (or any implementation of Jax-Rs 2.0) for the reference implementions, even though Core is no longer dependent on Jax-Rs implementation.

**Comment by jamsden** [comment]
Updated to Jetty 9.3 and now all the oslc4j Wink-based sample servers build and run correctly, even with lyo.core configured for JAX-RS 2.0 and Jersey.

**Comment by berezovskyi** [comment]
Update: we are using Lyo 2.4.0 and Lyo 4.0-SNAPSHOT libraries under JDK11 on Jetty 9.4 w/o any issues.
